---
- name: Format newly created volume
  community.windows.win_format:
    drive_letter: "{{ partition_result.drive_letter }}"
    file_system: "{{ fs_type }}"
    new_label: "{{ fs_label }}"
    force: true
  listen: Format new partition
